version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./SetupDB:/scripts
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "
      for script in /scripts/*.sql; do
        echo Running $script;
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P 'YourStrong!Passw0rd' -d master -i $script;
      done
      "
    mem_limit: 256m

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PicX=Server=db;Database=PicX;User=sa;Password=YourStrong!Passw0rd;
    ports:
      - "7162:7162"
    depends_on:
      - db
      - db-init
    mem_limit: 256m 